name: Test Compilation

on:
  push:

jobs:
  run-jpf:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '17' ]
    name: Java ${{ matrix.java }} Compile

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 71b1b30fa79610299a907bca3fed5834685f3942

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3  
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Empty space
      run: | 
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
        df -h
        echo "Removing large packages"
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y azure-cli google-cloud-cli hhvm google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        df -h
        docker system prune -af
        echo "Removing large directories"
        rm -rf /usr/share/dotnet/
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/local/*
        df -h
    - name: Compile Java sources
      run: |
        ./gradlew clean localDistro
